import React, { useState } from 'react';
import {
  Box, Typography, Paper, Chip, CircularProgress,
  Accordion, AccordionSummary, AccordionDetails,
  LinearProgress, List, ListItem, ListItemText, Divider, TextField
} from '@mui/material';
import { ExpandMore } from '@mui/icons-material';
import { useQuery } from '@tanstack/react-query';
import { rcaApi } from '../../api';
import type { RcaReport } from '../../types';
import dayjs from 'dayjs';

const CATEGORY_COLOR: Record<string, string> = {
  DEPLOYMENT: '#ff9800', CODE_BUG: '#f44336', INFRA: '#9c27b0',
  DEPENDENCY: '#2196f3', CONFIG: '#ff5722',
};

const ConfidenceBar: React.FC<{ value: number }> = ({ value }) => (
  <Box display="flex" alignItems="center" gap={1}>
    <LinearProgress variant="determinate" value={value * 100}
      sx={{ flex: 1, height: 6, borderRadius: 3,
        '& .MuiLinearProgress-bar': { bgcolor: value > 0.7 ? '#4caf50' : value > 0.4 ? '#ff9800' : '#f44336' } }} />
    <Typography variant="caption" color="grey.400">{(value * 100).toFixed(0)}%</Typography>
  </Box>
);

export const RcaPage: React.FC = () => {
  const [incidentId, setIncidentId] = useState('');
  const [searchId, setSearchId] = useState('');

  const { data: report, isLoading, isError } = useQuery<RcaReport>({
    queryKey: ['rca', searchId],
    queryFn: () => rcaApi.getLatest(searchId).then(r => r.data.data),
    enabled: searchId.length > 10,
  });

  return (
    <Box>
      <Typography variant="h5" color="white" fontWeight={700} mb={3}>🤖 AI Root Cause Analysis</Typography>

      <Box display="flex" gap={2} mb={3}>
        <TextField
          label="Enter Incident ID"
          value={incidentId}
          onChange={e => setIncidentId(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && setSearchId(incidentId)}
          InputLabelProps={{ sx: { color: 'grey.400' } }}
          InputProps={{ sx: { color: 'white' } }}
          sx={{ flex: 1, '& .MuiOutlinedInput-notchedOutline': { borderColor: '#444' } }}
        />
      </Box>

      {isLoading && <CircularProgress />}

      {report && (
        <Box display="flex" flexDirection="column" gap={2}>
          {/* Header */}
          <Paper sx={{ p: 2.5, bgcolor: '#1e1e3a', border: '1px solid #333' }}>
            <Box display="flex" justifyContent="space-between" flexWrap="wrap" gap={1}>
              <Box>
                <Typography color="grey.400" variant="caption">Generated by</Typography>
                <Typography color="white" fontWeight={600}>{report.generatedBy}</Typography>
              </Box>
              <Box>
                <Typography color="grey.400" variant="caption">Generated At</Typography>
                <Typography color="white" fontWeight={600}>{dayjs(report.generatedAt).format('YYYY-MM-DD HH:mm:ss')}</Typography>
              </Box>
              <Box>
                <Typography color="grey.400" variant="caption">Generation Time</Typography>
                <Typography color="white" fontWeight={600}>{report.generationMs}ms</Typography>
              </Box>
              <Box minWidth={200}>
                <Typography color="grey.400" variant="caption">Overall Confidence</Typography>
                <ConfidenceBar value={report.confidenceScore} />
              </Box>
            </Box>
          </Paper>

          {/* Root Causes */}
          <Paper sx={{ p: 2.5, bgcolor: '#1e1e3a' }}>
            <Typography variant="h6" color="white" mb={2}>🔍 Root Causes</Typography>
            {report.rootCauses.map((rc, i) => (
              <Box key={i} mb={2} p={2} sx={{ bgcolor: '#0f0f2a', borderRadius: 1, borderLeft: `3px solid ${CATEGORY_COLOR[rc.category] ?? '#90caf9'}` }}>
                <Box display="flex" alignItems="center" gap={1} mb={1}>
                  <Chip label={rc.category} size="small" sx={{ bgcolor: CATEGORY_COLOR[rc.category] + '33', color: CATEGORY_COLOR[rc.category] }} />
                  <ConfidenceBar value={rc.confidence} />
                </Box>
                <Typography color="white" fontWeight={600} mb={0.5}>{rc.description}</Typography>
                <Typography color="grey.400" variant="body2" fontStyle="italic">{rc.evidence}</Typography>
              </Box>
            ))}
          </Paper>

          {/* Impact & Timeline Summary */}
          <Paper sx={{ p: 2.5, bgcolor: '#1e1e3a' }}>
            <Typography variant="h6" color="white" mb={1}>💥 Impact Summary</Typography>
            <Typography color="grey.300" variant="body2">{report.impactSummary}</Typography>
            <Divider sx={{ my: 2, borderColor: '#333' }} />
            <Typography variant="h6" color="white" mb={1}>📅 Timeline Summary</Typography>
            <Typography color="grey.300" variant="body2">{report.timelineSummary}</Typography>
          </Paper>

          {/* Recovery Actions */}
          <Paper sx={{ p: 2.5, bgcolor: '#1e1e3a' }}>
            <Typography variant="h6" color="white" mb={2}>⚡ Recovery Actions</Typography>
            {[...report.recoveryActions].sort((a, b) => a.priority - b.priority).map((action, i) => (
              <Box key={i} mb={2} p={2} sx={{ bgcolor: '#0f0f2a', borderRadius: 1 }}>
                <Box display="flex" justifyContent="space-between" mb={1}>
                  <Chip label={`P${action.priority}`} size="small" color={action.priority === 1 ? 'error' : action.priority === 2 ? 'warning' : 'info'} />
                  <Box display="flex" gap={1}>
                    <Chip label={action.owner} size="small" variant="outlined" sx={{ color: 'grey.400' }} />
                    <Chip label={action.estimatedTime} size="small" variant="outlined" sx={{ color: 'grey.400' }} />
                  </Box>
                </Box>
                <Typography color="white" fontWeight={600}>{action.action}</Typography>
                <Typography color="grey.400" variant="body2" mt={0.5}>{action.rationale}</Typography>
              </Box>
            ))}
          </Paper>

          {/* Prevention Recommendations */}
          <Paper sx={{ p: 2.5, bgcolor: '#1e1e3a' }}>
            <Typography variant="h6" color="white" mb={2}>🛡️ Prevention Recommendations</Typography>
            <List dense>
              {report.preventionRecs.map((rec, i) => (
                <ListItem key={i} sx={{ '&:before': { content: '"→"', color: '#90caf9', mr: 1 } }}>
                  <ListItemText primary={rec} primaryTypographyProps={{ color: 'grey.300', variant: 'body2' }} />
                </ListItem>
              ))}
            </List>
          </Paper>
        </Box>
      )}
    </Box>
  );
};
